service: bus-tickets-booking
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:sa-east-1:629386865707:table/User

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi:
          path: /
          method: get
  addUser:
    handler: src/addUser.addUser
    events:
      - httpApi:
          path: /users
          method: post

resources:
  Resources:
    TaskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: User
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH