service: bus-tickets-booking
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - { "Fn::GetAtt": ["UserTable", "Arn"] }
        - { "Fn::GetAtt": ["BusTable", "Arn"] }

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi:
          path: /
          method: get
  addUser:
    handler: src/addUser.addUser
    events:
      - httpApi:
          path: /users
          method: post
  getUsers:
    handler: src/getUsers.getUsers
    events:
      - httpApi:
          path: /users
          method: get
  addBus:
    handler: src/addBus.addBus
    events:
      - httpApi:
          path: /buses
          method: post

resources:
  Resources:
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UserTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    BusTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: BusTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH